### ISSUE TITLE
Mein Versuch war richtig, dennoch wird mir ein Versuch abgezogen

### ISSUE THREAD

**Issue by dermodmaster** [xGRKE/Hangman#1]
So eine scheiße!!1111elf

**Comment by Alizame** [comment]
ooof

**Comment by Alizame** [comment]
vielleicht weil dus verdient hast¿

**Comment by Alizame** [comment]
ok confirmed

**Comment by dermodmaster** [comment]
Siehst du - es liegt nicht nur an meiner Persönlichkeit... also auch aber nicht nur!!!1elf
