### ISSUE TITLE
Käis Sensentif

### ISSUE THREAD

**Issue by dermodmaster** [xGRKE/Hangman#5]
Wieso ist die Eingabe fooocking Käis sensentive

**Comment by dermodmaster** [comment]
Das ist against the rulez

**Comment by Alizame** [comment]
das ist der Dr. Dr. Marten faktor, special variante!!
z.b. wenn 2 t in einem wort sind, kann man das 2. t nicht aufdecken
und dann verliert man halt automatisch weil pech

**Comment by dermodmaster** [comment]
Very Pech, much wow

**Comment by Alizame** [comment]
@dermodmaster #4 ist vollbracht!!
